# Generated by Django 5.0.2 on 2024-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_editora"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editora",
            name="descricao",
        ),
        migrations.AddField(
            model_name="editora",
            name="nome",
            field=models.CharField(default="...", max_length=100),
        ),
        migrations.AddField(
            model_name="editora",
            name="site",
            field=models.URLField(blank=True, null=True),
        ),
    ]
