# Generated by Django 5.0.2 on 2024-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_editora_descricao_editora_nome_editora_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(default="...", max_length=100)),
                ("email", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
